// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB8t8rpgxGy2CgcXkRjlV74PQwt7gZ6jo',
    appId: '1:879098759847:web:90ed9e391c9f885612e982',
    messagingSenderId: '879098759847',
    projectId: 'campus-thrift',
    authDomain: 'campus-thrift.firebaseapp.com',
    storageBucket: 'campus-thrift.firebasestorage.app',
    measurementId: 'G-MZDN7CTH6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB3QVBghJkREiKVQd9Ulwlatzbe0ibFRI',
    appId: '1:879098759847:android:d7da438f240545e112e982',
    messagingSenderId: '879098759847',
    projectId: 'campus-thrift',
    storageBucket: 'campus-thrift.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX5jWTx3U_IyxnLe4BMNA5fx-srVDZ4bU',
    appId: '1:879098759847:ios:262b54fd6733269b12e982',
    messagingSenderId: '879098759847',
    projectId: 'campus-thrift',
    storageBucket: 'campus-thrift.firebasestorage.app',
    iosBundleId: 'com.example.campusThriftApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX5jWTx3U_IyxnLe4BMNA5fx-srVDZ4bU',
    appId: '1:879098759847:ios:262b54fd6733269b12e982',
    messagingSenderId: '879098759847',
    projectId: 'campus-thrift',
    storageBucket: 'campus-thrift.firebasestorage.app',
    iosBundleId: 'com.example.campusThriftApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB8t8rpgxGy2CgcXkRjlV74PQwt7gZ6jo',
    appId: '1:879098759847:web:b67dd26f4403093812e982',
    messagingSenderId: '879098759847',
    projectId: 'campus-thrift',
    authDomain: 'campus-thrift.firebaseapp.com',
    storageBucket: 'campus-thrift.firebasestorage.app',
    measurementId: 'G-84YJFJ6F4D',
  );
}
